[2020-06-08 19:22:36,925] {taskinstance.py:669} INFO - Dependencies all met for <TaskInstance: my_dag.source3 2020-06-08T13:49:42.367179+00:00 [queued]>
[2020-06-08 19:22:36,935] {taskinstance.py:669} INFO - Dependencies all met for <TaskInstance: my_dag.source3 2020-06-08T13:49:42.367179+00:00 [queued]>
[2020-06-08 19:22:36,935] {taskinstance.py:879} INFO - 
--------------------------------------------------------------------------------
[2020-06-08 19:22:36,935] {taskinstance.py:880} INFO - Starting attempt 1 of 2
[2020-06-08 19:22:36,935] {taskinstance.py:881} INFO - 
--------------------------------------------------------------------------------
[2020-06-08 19:22:36,952] {taskinstance.py:900} INFO - Executing <Task(PythonOperator): source3> on 2020-06-08T13:49:42.367179+00:00
[2020-06-08 19:22:36,957] {standard_task_runner.py:53} INFO - Started process 12502 to run task
[2020-06-08 19:22:37,035] {logging_mixin.py:112} INFO - Running %s on host %s <TaskInstance: my_dag.source3 2020-06-08T13:49:42.367179+00:00 [running]> nineleaps-ThinkPad-E470
[2020-06-08 19:22:37,131] {taskinstance.py:1145} ERROR - 'ti'
Traceback (most recent call last):
  File "/home/nineleaps/.local/lib/python2.7/site-packages/airflow/models/taskinstance.py", line 983, in _run_raw_task
    result = task_copy.execute(context=context)
  File "/home/nineleaps/.local/lib/python2.7/site-packages/airflow/operators/python_operator.py", line 113, in execute
    return_value = self.execute_callable()
  File "/home/nineleaps/.local/lib/python2.7/site-packages/airflow/operators/python_operator.py", line 118, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/home/nineleaps/airflow/dags/airflow_tasks.py", line 81, in percentage_upload
    ti = kwargs['ti']
KeyError: 'ti'
[2020-06-08 19:22:37,132] {taskinstance.py:1168} INFO - Marking task as UP_FOR_RETRY
[2020-06-08 19:22:46,918] {logging_mixin.py:112} INFO - [2020-06-08 19:22:46,918] {local_task_job.py:103} INFO - Task exited with return code 1
